name: User Service CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
  security-events: write
  packages: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: user-service
  JAVA_VERSION: 17
  POSTGRES_DB: user-service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Server123@

jobs:
  # -----------------------------
  # 1. Build and Test
  # -----------------------------
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d user-service"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ env.POSTGRES_USER }}; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run Unit Tests
        run: ./gradlew test --no-daemon --info
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${{ env.POSTGRES_DB }}
          SPRING_DATASOURCE_USERNAME: ${{ env.POSTGRES_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ env.POSTGRES_PASSWORD }}

      - name: Run Integration Tests
        run: ./gradlew integrationTest --no-daemon || echo "No integration tests found"
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${{ env.POSTGRES_DB }}
          SPRING_DATASOURCE_USERNAME: ${{ env.POSTGRES_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ env.POSTGRES_PASSWORD }}

      - name: Build Application
        run: ./gradlew bootJar -x test --no-daemon

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts-${{ github.run_number }}
          path: build/libs/*.jar
          retention-days: 1

  # -----------------------------
  # 2. Docker Build & Push
  # -----------------------------
  build-docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifacts
        uses: actions/download-artifact@v4
        with:
          name: jar-artifacts-${{ github.run_number }}
          path: build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: godfrey10
          password: godfreygrace10

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=commit-
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=User Service
            org.opencontainers.image.description=Spring Boot User Microservice
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.simple
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # -----------------------------
  # 3. Deploy to Development
  # -----------------------------
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.ref == 'refs/heads/develop'
    environment:
      name: development
      url: http://dev.user-service.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to Development
        run: |
          echo "🚀 Deploying development..."
          echo "Using Docker image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          # Example: docker-compose -f docker-compose.dev.yml up -d
          echo "✅ Development deployment completed"

  # -----------------------------
  # 4. Deploy to Production
  # -----------------------------
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: http://user-service.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to Production
        run: |
          echo "🚀 Deploying production..."
          echo "Using Docker image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          # Example: docker-compose -f docker-compose.prod.yml up -d
          echo "✅ Production deployment completed"

  # -----------------------------
  # 5. Cleanup
  # -----------------------------
  cleanup:
    runs-on: ubuntu-latest
    needs: [build-and-test, build-docker, deploy-dev, deploy-prod]
    if: always()
    steps:
      - name: Clean up artifacts
        run: |
          echo "🧹 Cleaning up temporary artifacts..."
          echo "✅ Cleanup completed"

  # -----------------------------
  # 6. Notifications
  # -----------------------------
  notify:
    runs-on: ubuntu-latest
    needs: [deploy-dev, deploy-prod, cleanup]
    if: always()
    steps:
      - name: Notify Deployment Status
        run: |
          echo "📊 Pipeline Results:"
          if [[ "${{ needs.deploy-prod.result }}" == "success" ]]; then
            echo "🎉 Production deployment successful!"
          elif [[ "${{ needs.deploy-dev.result }}" == "success" ]]; then
            echo "🚀 Development deployment successful!"
          else
            echo "❌ Deployment failed or skipped!"
