name: User Service CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: godfrey10/user-service
  JAVA_VERSION: 17
  POSTGRES_DB: user-service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Server123@

jobs:
  # -----------------------------
  # 1. Build and Test
  # -----------------------------
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: user-service
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Server123@
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d user-service"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run Unit Tests with Coverage
        run: ./gradlew test jacocoTestReport --no-daemon --info
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/user-service
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: Server123@

      - name: Build Application
        run: ./gradlew bootJar -x test --no-daemon

      - name: Upload test results and coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: |
            build/test-results/test/
            build/reports/jacoco/test/
            build/reports/tests/test/
          retention-days: 1

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts-${{ github.run_number }}
          path: build/libs/*.jar
          retention-days: 1

  # -----------------------------
  # 2. SonarQube Analysis
  # -----------------------------
  sonar-analysis:
    runs-on: ubuntu-latest
    needs: build-and-test
    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl -f http://localhost:9000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Download test results and coverage
        uses: actions/download-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: build/

      - name: Wait for SonarQube
        run: |
          echo "Waiting for SonarQube..."
          until curl -s http://localhost:9000/api/system/health | grep -q "\"status\":\"GREEN\""; do
            echo "Waiting..."
            sleep 5
          done

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: sqp_3f88a9480299b6dccca3522bef2fdd3fa4336f65

        run: |
          ./gradlew sonar \
            -Dsonar.projectKey=user-service \
            -Dsonar.projectName='User Service' \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.java.binaries=build/classes/java/main \
            -Dsonar.junit.reportPaths=build/test-results/test \
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

    # -----------------------------
  # 3. Docker Build & Push
  # -----------------------------
  build-docker:
    runs-on: ubuntu-latest
    needs: sonar-analysis
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifacts
        uses: actions/download-artifact@v4
        with:
          name: jar-artifacts-${{ github.run_number }}
          path: build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: godfrey10
          password: godfreygrace10

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.simple
          push: true
          tags: godfrey10/user-service:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # -----------------------------
  # 4. Deploy Production
  # -----------------------------
  deploy-production:
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Pull latest image
        run: docker pull godfrey10/user-service:latest

      - name: Stop and remove old container
        run: |
          docker stop userservice-prod 2>/dev/null || true
          docker rm userservice-prod 2>/dev/null || true

      - name: Run container
        run: |
          docker run -d --name userservice-prod \
            -p 8081:8081 \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/user-service \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=Server123@ \
            godfrey10/user-service:latest

      - name: Verify container
        run: docker logs userservice-prod --tail 20
