name: User Service CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read

env:
  IMAGE_NAME: godfrey10/user-service
  JAVA_VERSION: 17
  GRADLE_VERSION: 8.5
  POSTGRES_DB: user-service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Server123@

jobs:
  # -----------------------------
  # 1. Build and Test
  # -----------------------------
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d ${{ env.POSTGRES_DB }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ env.POSTGRES_USER }}; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run Unit Tests
        run: ./gradlew test --no-daemon --info
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${{ env.POSTGRES_DB }}
          SPRING_DATASOURCE_USERNAME: ${{ env.POSTGRES_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ env.POSTGRES_PASSWORD }}

      - name: Build JAR
        run: ./gradlew bootJar -x test --no-daemon

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts-${{ github.run_number }}
          path: build/libs/*.jar
          retention-days: 1

  # -----------------------------
  # 2. Docker Build & Push
  # -----------------------------
  build-docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifacts
        uses: actions/download-artifact@v4
        with:
          name: jar-artifacts-${{ github.run_number }}
          path: build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: godfrey10
          password: godfreygrace10

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: godfrey10/user-service:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # -----------------------------
  # 3. Security Scan
  # -----------------------------
  security-scan:
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.event_name == 'push'
    steps:
      - name: Pull Docker image
        run: docker pull godfrey10/user-service:latest

      - name: Run security scan with Trivy
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --exit-code 1 \
            --severity HIGH,CRITICAL \
            godfrey10/user-service:latest

  # -----------------------------
  # 4. Deploy Production
  # -----------------------------
  deploy-production:
    runs-on: ubuntu-latest
    needs: [build-docker, security-scan]
    if: github.ref == 'refs/heads/main'
    environment: production
    timeout-minutes: 10
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: godfrey10
          password: godfreygrace10

      - name: Pull latest image
        run: docker pull godfrey10/user-service:latest

      - name: Stop and remove old container
        run: |
          docker stop userservice-prod 2>/dev/null || true
          docker rm userservice-prod 2>/dev/null || true

      - name: Run container
        run: |
          docker run -d --name userservice-prod \
            -p 8081:8081 \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/user-service \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=Server123@ \
            godfrey10/user-service:latest

      - name: Verify container
        run: docker logs userservice-prod --tail 20

  # -----------------------------
  # 5. Cleanup
  # -----------------------------
  cleanup:
    runs-on: ubuntu-latest
    needs: [build-and-test, build-docker, security-scan, deploy-production]
    if: always()
    steps:
      - name: Cleanup Docker
        run: |
          docker system prune -af || true
          docker volume prune -f || true
          rm -rf build/ || true

  # -----------------------------
  # 6. Notifications
  # -----------------------------
  notify:
    runs-on: ubuntu-latest
    needs: [deploy-production, cleanup]
    if: always()
    steps:
      - name: Notify Deployment
        run: |
          if [[ "${{ needs.deploy-production.result }}" == "success" ]]; then
            echo "🎉 Production deployment successful!"
          else
            echo "⚠️ Deployment failed!"
          fi
